export const GET_LECTURER_LIST = 'app/student/appointment/GET_USERS'
export const SET_LECTURER_LIST = 'app/student/appointment/SET_TO_USERS'
export const GET_REQUEST_APPOINTMENT = 'app/lecturer/appointment/GET_REQUEST_APPOINTMENT'
export const SET_REQUEST_APPOINTMENT = 'app/lecturer/appointment/SET_REQUEST_APPOINTMENT'
export const APPROVE_APPOINTMENT = 'app/lecturer/appointment/APPROVE_APPOINTMENT'
export const REJECT_APPOINTMENT = 'app/lecturer/appointment/REJECT_APPOINTMENT'
export const SUCCESS_APPROVE_APPOINTMENT = 'app/lecturer/appointment/SUCCESS_APPROVE_APPOINTMENT'
